name: 'Nuget Release'

on:
  push:
    tags:
    - '*'
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: './Dirigera.Lib/Dirigera.Lib.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:PackageVersion='${{github.ref_name}}' --no-restore

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
